### ISSUE TITLE
[Bug] Export project button crashes app (and export app doesn't work)

### ISSUE THREAD

**Issue by Pe13** [fridakitten/FridaCodeManager#11]
I'm on dopamine roothide iPadOS 16.6

Actually export app seems to just build the project

**Comment by fridakitten** [comment]
Fixed for roothide and rootless

**Comment by Pe13** [comment]
I'd like to tell you that it doesn't crash anymore, but it still crashes

**Comment by fridakitten** [comment]
That is not possible.

**Comment by Pe13** [comment]
[swifty-2024-10-14-111133.txt](https://github.com/user-attachments/files/17361702/swifty-2024-10-14-111133.txt)
The file is actually an ips but I couldn't upload it as it was, so I just changed the extension
I pulled just before building.

**Comment by Pe13** [comment]
Just to better report the behavior:
Now export project shows an "alert" before the crash and export app crashes the app too after showing the "alert"

**Comment by fridakitten** [comment]
It’s a iPad-only related Bug. I cannot fix it.

in case this doesn’t work I cannot assist:
[_com.apple.Pasteboard.BoY8BO.zip](https://github.com/user-attachments/files/17364271/_com.apple.Pasteboard.BoY8BO.zip)

Its because it seems iPad handle View hierarchies in a stupid way.

**Comment by Pe13** [comment]
Sorry for the late reply, I think you didn't built the package for roothide, since it complains about arm64 arch instead of arm64e

**Comment by fridakitten** [comment]
Thats bullshit. The arm64e binary architecture is incompatible with your iPad. The app crashing has nothing to do with the package build.

**Comment by Pe13** [comment]
I mean that I can't install the deb you send me

**Comment by fridakitten** [comment]
Issue is fixed on FCM v1.7
![IMG_0048](https://github.com/user-attachments/assets/1bb6a387-0db9-4406-be2f-31fc5d8e3aa7)
