### ISSUE TITLE
SDK 15.6 cant download from polcom.de

### ISSUE THREAD

**Issue by ghh-jb** [fridakitten/FridaCodeManager#26]
Seems like there is no such file on server.

**Comment by fridakitten** [comment]
server currently offline, wait on FridaCodeManager 2.0 ;)

**Comment by ghh-jb** [comment]
Hah... Ok...

I just tried to compile it on Fugu15_Rootful but... I was not able to download SDK 15.6 from polcom.de

**Comment by fridakitten** [comment]
because its not at polcom.de anymore

**Comment by ghh-jb** [comment]
> because its not at polcom.de anymore

However, in makefile it is. I cant compile it.

**Comment by fridakitten** [comment]
will fix

**Comment by ghh-jb** [comment]
hope so...

**Comment by ItzMatty3241** [comment]
Lol why is everyone so mean when things donesnt go exactly how they want?! Its completely free and olen source no one thanked her for doing such a great job this is way better than using theos btw one suggestion is add option to create tweaks as well ? And lastly but not less important thank you so much for your hard work 🙂

**Comment by ghh-jb** [comment]
> Lol why is everyone so mean when things donesnt go exactly how they want?! Its completely free and olen source no one thanked her for doing such a great job this is way better than using theos btw one suggestion is add option to create tweaks as well ? And lastly but not less important thank you so much for your hard work 🙂

Because i want to port this thing to rootful ios 15+ and becaue of sdk i cant do that. I really appreciate their work but u know, it is also very hard to hear that "rootful is dead use rootless" when i was fixing Fugu15_Rootful. Now I use it but i want this app, and it cant build. That is disappointing.

**Comment by fridakitten** [comment]
Bro just fork and build it your self, the bug is already fixed

**Comment by fridakitten** [comment]
fix it your self

**Comment by ghh-jb** [comment]
> fix it your self

So ye, you did NOT fix it lol, why were you lying to yourself...

**Comment by fridakitten** [comment]
no, I was upset

**Comment by ghh-jb** [comment]
> no, I was upset

So you say me to fix it because you cant? Ok then, where can i get ar archiving utility? What package? There is no binutils like in linux.

**Comment by fridakitten** [comment]
bro, clone it again and use the makefile damn

**Comment by fridakitten** [comment]
typical, r/jb fanboy!

**Comment by fridakitten** [comment]
https://github.com/fridakitten/FridaCodeManager/commit/d4e3033656991bd0d6a6b7a0a0f20d6d2ecffcbc

**Comment by ghh-jb** [comment]
> typical, r/jb fanboy!

Heh, not really, not every user on iOS 15.0-15.4.1 use Fugu15_Rootful with self-fix lol
